apiVersion: v1
kind: ReplicationController
metadata:
  name: aggregator
spec:
  replicas: 1
  selector:
    app: aggregator
  template:
    metadata:
      labels:
        app: aggregator
    spec:
      containers:
      - name: aggregator
        image: 52.34.61.67:80/apihealth-ui # check
        command: ['supervisord']

        env:
        - name: AGGREGATOR_RELEASE
          value: latest

        - name: PNAME
          value: apihealth_aggregator

        - name: ENVNAME
          value: dev

        - name: LOGLEVEL
          value: info

        - name: pghost
          value: 52.72.48.33 

        - name: pguser
          value: postgres

        - name: pgpwd
          value: postgres

        - name: redishost
          value: 52.73.83.42

        - name: redisport
          value: "6377"


 #/usr/bin/docker run --rm -e PNAME=apihealth_aggregator -e DOCKER_HOST=${COREOS_PRIVATE_IPV4} -e ENVNAME=production -e LOGLEVEL=info -e pguser={{ apihealth_external['pguser'] }} -e pgpwd={{ apihealth_external['pgpwd'] }} -e redishost={{ apihealth_external['region'][instanceregion.stdout]['uiredishost'] }} --name aggregator_{{ item }} -v /var/log/apihealth:/var/log/apihealth -v /var/log/supervisor:/var/log/supervisor {{ docker_repo['name'] }}:{{ docker_repo['port'] }}/apihealth-ui:$AGGREGATOR_RELEASE supervisord

 






