apiVersion: v1
kind: ReplicationController
metadata:
  name: ms
spec:
  replicas: 1
  selector:
    app: ms
  template:
    metadata:
      labels:
        app: ms
    spec:
      containers:
      - name: ms
        image: 52.34.61.67:80/apihealth-ui # check
        command: ['supervisord']

        env:
        - name: MS_RELEASE
          value: latest

        - name: PNAME
          value: apihealth_ms

        - name: ENVNAME
          value: dev

        - name: LOGLEVEL
          value: info

        - name: pghost
          value: 52.72.48.33 

        - name: pguser
          value: postgres

        - name: pgpwd
          value: postgres

        - name: redishost
          value: 52.73.83.42

        - name: redisport
          value: "6377"




#DOCKER_HOST=${COREOS_PRIVATE_IPV4} -e ENVNAME=production -e LOGLEVEL=info -e pguser={{ apihealth_external['pguser'] }} -e pgpwd={{ apihealth_external['pgpwd'] }} -p {{ apihealth_external['ms']['base'] }}{{ item }}:{{ apihealth_external['ms']['port'] }} -e redishost={{ apihealth_external['region'][instanceregion.stdout]['uiredishost'] }} --name ms_{{ item }} -v /var/log/apihealth:/var/log/apihealth -v /var/log/supervisor:/var/log/supervisor {{ docker_repo['name'] }}:{{ docker_repo['port'] }}/apihealth-ui:$MS_RELEASE supervisord'

