apiVersion: v1
kind: ReplicationController
metadata:
  name: ui
spec:
  replicas: 2
  selector:
    app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: 52.34.61.67:80/apihealth-ui
        command: ['supervisord']
        ports:
        - containerPort: 8080

        env:
        - name: UI_RELEASE
          value: latest

        - name: PNAME
          value: apihealth_ui 

        - name: ENVNAME
          value: dev

        - name: LOGLEVEL
          value: info

        - name: pghost
          value: 52.72.48.33 

        - name: pguser
          value: postgres

        - name: pgpwd
          value: postgres

        - name: admin_basic_auth
          value: YWgtbWg0NjczOGlvX3Byb2RAYXBpZ2VlLmNvbTpNaCQ2NzMqaU8

        - name: redishost
          value: 52.73.83.42

        - name: redisport
          value: "6377"

#/bin/bash -c '/usr/bin/docker run --rm -e UI_RELEASE=latest -e PNAME=apihealth_ui -e DOCKER_HOST=${COREOS_PRIVATE_IPV4} -e ENVNAME=e2e -e LOGLEVEL=info -e pguser={{ apihealth_external['pguser'] }} -e pgpwd={{ apihealth_external['pgpwd'] }} -p {{ apihealth_external['ui']['base'] }}{{ item }}:{{ apihealth_external['ui']['port'] }}  -e admin_basic_auth={{ apihealth_external['admin_basic_auth'] }} -e redishost={{ apihealth_external['region'][instanceregion.stdout]['redishost'] }} --name ui_{{ item }} -v /var/log/apihealth:/var/log/apihealth -v /var/log/supervisor:/var/log/supervisor {{ docker_repo['name'] }}:{{ docker_repo['port'] }}/apihealth-ui:$UI_RELEASE supervisord'








